In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
import joblib
from sklearn.preprocessing import OrdinalEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

In [ ]:
data = pd.read_csv("/content/student_dataset_200.csv")
data.head()

    Name  Roll No             Description         Level
0  Rahul      101  strong problem solving      Advanced
1   Ravi      102          weak in basics      Beginner
2   Ravi      103  strong problem solving      Advanced
3   Anil      104   average understanding  Intermediate
4  Sneha      105            slow learner      Beginner

In [ ]:
data.shape

(200, 4)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         200 non-null    object
 1   Roll No      200 non-null    int64
 2   Description  200 non-null    object
 3   Level        200 non-null    object
dtypes: int64(1), object(3)
memory usage: 6.4+ KB

In [ ]:
data.isnull().sum()

Name           0
Roll No        0
Description    0
Level          0
dtype: int64

In [ ]:
data.drop("Name",axis=1,inplace=True)
data.drop("Roll No",axis=1,inplace=True)

In [ ]:
data.head()

              Description         Level
0  strong problem solving      Advanced
1          weak in basics      Beginner
2  strong problem solving      Advanced
3   average understanding  Intermediate
4            slow learner      Beginner

In [ ]:
tfidf = TfidfVectorizer(ngram_range=(1,2), stop_words='english')
X = tfidf.fit_transform(data["Description"])

In [ ]:
odr_enc = OrdinalEncoder()
y = odr_enc.fit_transform(data[["Level"]])

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [ ]:
logistic = LogisticRegression(max_iter=1000)
logistic.fit(X_train,y_train)

LogisticRegression(max_iter=1000)

In [ ]:
y_test_pred = logistic.predict(X_test)
y_test_pred

array([2., 0., 0., 2., 2., 1., 2., 2., 2., 1., 1., 1., 0., 0., 1., 0., 0.,
       2., 1., 2., 0., 2., 1., 1., 2., 1., 2., 0., 2., 0., 0., 2., 2., 0.,
       2., 0., 1., 0., 1., 1.])

In [ ]:
print("Training Score:", logistic.score(X_train, y_train))
print("Testing Score:", logistic.score(X_test, y_test))

Training Score: 1.0
Testing Score: 1.0

In [ ]:
print(classification_report(y_test, y_test_pred))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        13
         1.0       1.00      1.00      1.00        12
         2.0       1.00      1.00      1.00        15

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40

In [ ]:
new_text = ["struggles with basic concepts"]
new_vector = tfidf.transform(new_text)
prediction = logistic.predict(new_vector)
print("Predicted Level:", prediction)

Predicted Level: [1.]

In [ ]:
print(odr_enc.inverse_transform(prediction.reshape(-1, 1)))

[['Beginner']]

In [ ]:
joblib.dump(logistic, "model.pkl")
joblib.dump(tfidf, "tfidf.pkl")
joblib.dump(odr_enc, "encoder.pkl")

['encoder.pkl']

In [ ]:
print(tfidf.transform(["test sentence"]))

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 0 stored elements and shape (1, 54)>